### ISSUE TITLE
install with curunt chatwoot

### ISSUE THREAD

**Issue by Double-Click-ERP** [douglara/chatwoot-botpress-bridge#12]
Hello ,
Thank you for this bridge 

now i have already installed and running chatwoot ( local VM ), and i need to install botpress and use your bridge

but i have some questions 

1- can i use botpress with WhatsApp channel ?

2- can i install botpress on another VM  , after that use your bridge ? or you prefer to install on the same chatwoot VM ?

3- what is the BOTPRESS_ENDPOINT and CHATWOOT_ENDPOINT ?

Thank You

**Comment by douglara** [comment]
Hello friend

1 - Yes, after configuration you can use bots with any chatwoot channel

2 - You can install in same VM or in other, they just need to be able to comunicate
If you want test I recommend use this article:
https://www-linkedin-com.translate.goog/pulse/subindo-um-ambiente-de-desenvolvimento-chatbot-poderoso-douglas-lara/?_x_tr_sl=pt&_x_tr_tl=en&_x_tr_hl=pt-BR&_x_tr_pto=wapp

3 - This is address for botpress and chatwoot, depending on how you install could it be a url, ip or local address, example:
https://app.chatwoot.com

Any question let me know 🖖

**Comment by Double-Click-ERP** [comment]
Hello friend ,
Thank you for your help .

> Start server:
>> rails s

i got this error with the above step :

> Your Ruby version is 3.0.2, but your Gemfile specified 3.0.3


this is what i have done so fare :

1. new VM
2. install botpress  from (https://s3.amazonaws.com/botpress-binaries/botpress-v12_30_8-linux-x64.zip)
3. followed these steps (https://github.com/douglara/chatwoot-botpress-bridge#running-local)

**Comment by douglara** [comment]
> Hello friend , Thank you for your help .
> 
> > Install dependencies
> 
> > > bundle install
> 
> i got this error with the above step :
> 
> > Command 'bundle' not found, but can be installed with:
> > sudo snap install ruby          # version 3.2.2, or
> > sudo apt  install ruby-bundler  # version 2.3.5-2
> > See 'snap info ruby' for additional versions.
> 
> after fix it :
> 
> > $ sudo snap install ruby
> > error: This revision of snap "ruby" was published using classic confinement and
> > thus may perform arbitrary system changes outside of the security
> > sandbox that snaps are usually confined to, which may put your system at
> > risk.
> > If you understand and want to proceed repeat the command including
> > --classic.
> 
> > $ snap install ruby --classic
> > ruby 3.2.2 from Ruby core team (rubylang✓) installed
> 
> i got this error :
> 
> > $ bundle install
> > Bundler 2.4.10 is running, but your lockfile was generated with 2.3.15. Installing Bundler 2.3.15 and restarting using that version.
> > Fetching gem metadata from https://rubygems.org/.
> > Fetching bundler 2.3.15
> > Installing bundler 2.3.15
> > Your Ruby version is 3.2.2, but your Gemfile specified 3.0.3
> 
> this is what i have done so fare :
> 
> 1. new VM
> 2. install botpress  from (https://s3.amazonaws.com/botpress-binaries/botpress-v12_30_8-linux-x64.zip)
> 3. Creating bot in Botpress & Chatwoot
> 4. followed these steps (https://github.com/douglara/chatwoot-botpress-bridge#running-local)

Hi friend, its because bridge uses ruby version 3.0.3 and current chatwoot uses version 3.2.2
Do you needs two versions runs simultaneously, I dont know exaclty how to do it in RVM I use asdf.
You can ask help to in Telegram group too: https://t.me/chatwoot_botpress_bridge

**Comment by Double-Click-ERP** [comment]
Hi friend,
ok i will try from beginning using asdf , any suggestions on that ?

**Comment by Double-Click-ERP** [comment]
this is what i have done so fare :

1. new VM
2. install botpress from (https://s3.amazonaws.com/botpress-binaries/botpress-v12_30_8-linux-x64.zip)
3. Creating bot in Botpress & Chatwoot
4. install ruby 3.0.3 (https://itslinuxfoss.com/install-ruby-ubuntu-22-04/) (Method 3)
5. followed these steps (https://github.com/douglara/chatwoot-botpress-bridge#running-local)

.env:
> BOTPRESS_ENDPOINT=127.0.0.1
BOTPRESS_BOT_ID=chatwoot
CHATWOOT_ENDPOINT=10.0.0.69
CHATWOOT_BOT_TOKEN= XXXXXX

> gem install bundler:2.3.15
bundle install

i got this error :
rails s

>=> Booting Puma
>=> Rails 7.0.4.2 application starting in development 
>=> Run `bin/rails server --help` for more startup options
 >Puma starting in single mode...
>* Puma version: 5.6.5 (ruby 3.0.3-p157) ("Birdie's Version")
>*  Min threads: 5
>*  Max threads: 5
>*  Environment: development
>*  PID: 70511
>Exiting
/home/bot/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/puma-5.6.5/lib/puma/binder.rb:341:in `initialize': Address already in use - bind(2) for "127.0.0.1" port 3000 (Errno::EADDRINUSE)
	from /home/bot/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/puma-5.6.5/lib/puma/binder.rb:341:in `new'
	from /home/bot/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/puma-5.6.5/lib/puma/binder.rb:341:in `add_tcp_listener'
	from /home/bot/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/puma-5.6.5/lib/puma/binder.rb:335:in `block in add_tcp_listener'
	from /home/bot/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/puma-5.6.5/lib/puma/binder.rb:334:in `each'
	from /home/bot/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/puma-5.6.5/lib/puma/binder.rb:334:in `add_tcp_listener'
	from /home/bot/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/puma-5.6.5/lib/puma/binder.rb:173:in `block in parse'
	from /home/bot/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/puma-5.6.5/lib/puma/binder.rb:156:in `each'
	from /home/bot/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/puma-5.6.5/lib/puma/binder.rb:156:in `parse'
	from /home/bot/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/puma-5.6.5/lib/puma/runner.rb:156:in `load_and_bind'
	from /home/bot/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/puma-5.6.5/lib/puma/single.rb:44:in `run'
	from /home/bot/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/puma-5.6.5/lib/puma/launcher.rb:193:in `run'
	from /home/bot/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/puma-5.6.5/lib/rack/handler/puma.rb:72:in `run'
	from /home/bot/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rack-2.2.6.2/lib/rack/server.rb:327:in `start'
	from /home/bot/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.4.2/lib/rails/commands/server/server_command.rb:38:in `start'
	from /home/bot/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.4.2/lib/rails/commands/server/server_command.rb:143:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /home/bot/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.4.2/lib/rails/commands/server/server_command.rb:134:in `perform'
	from /home/bot/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/bot/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/bot/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/bot/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.4.2/lib/rails/command/base.rb:87:in `perform'
	from /home/bot/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.4.2/lib/rails/command.rb:48:in `invoke'
	from /home/bot/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-7.0.4.2/lib/rails/commands.rb:18:in `<main>'
	from /home/bot/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/bot/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'

closing terminal that used for for install Botpress , made the apov comand run like that 

rails s

>=> Booting Puma
>=> Rails 7.0.4.2 application starting in development 
>=> Run `bin/rails server --help` for more startup options
>Puma starting in single mode...
>* Puma version: 5.6.5 (ruby 3.0.3-p157) ("Birdie's Version")
>*  Min threads: 5
>*  Max threads: 5
>*  Environment: development
>*  PID: 71535
>* Listening on http://127.0.0.1:3000
>* Listening on http://[::1]:3000
>Use Ctrl-C to stop


rails test

> Running 20 tests in a single process (parallelization threshold is 50)
Run options: --seed 32167
Running:
E
Error:
ReceiveEventTest#test_success:
Addressable::URI::InvalidURIError: Absolute URI missing hierarchical segment: 'http://:80'
    app/use_cases/chatwoot/send_to_botpress.rb:21:in `call!'
    app/use_cases/chatwoot/receive_event.rb:28:in `process_event'
    app/use_cases/chatwoot/receive_event.rb:7:in `call!'
    test/use_cases/chatwoot/receive_event_test.rb:14:in `block in <class:ReceiveEventTest>'
    test/support/vcr.rb:38:in `instance_eval'
    test/support/vcr.rb:38:in `block (2 levels) in test'
    test/support/vcr.rb:37:in `block in test'
rails test test/support/vcr.rb:36
.E
Error:
ReceiveEventTest#test_botpress_two_mesasges:
Addressable::URI::InvalidURIError: Absolute URI missing hierarchical segment: 'http://:80'
    app/use_cases/chatwoot/send_to_botpress.rb:21:in `call!'
    app/use_cases/chatwoot/receive_event.rb:28:in `process_event'
    app/use_cases/chatwoot/receive_event.rb:7:in `call!'
    test/use_cases/chatwoot/receive_event_test.rb:31:in `block in <class:ReceiveEventTest>'
    test/support/vcr.rb:38:in `instance_eval'
    test/support/vcr.rb:38:in `block (2 levels) in test'
    test/support/vcr.rb:37:in `block in test'
rails test test/support/vcr.rb:36
...E
Error:
ChatwootControllerTest#test_success:
Addressable::URI::InvalidURIError: Absolute URI missing hierarchical segment: 'http://:80'
    app/use_cases/chatwoot/send_to_botpress.rb:21:in `call!'
    app/use_cases/chatwoot/receive_event.rb:28:in `process_event'
    app/use_cases/chatwoot/receive_event.rb:7:in `call!'
    app/controllers/chatwoot_controller.rb:3:in `webhook'
    test/controllers/chatwoot_controller_test.rb:11:in `block in <class:ChatwootControllerTest>'
    test/support/vcr.rb:38:in `instance_eval'
    test/support/vcr.rb:38:in `block (2 levels) in test'
    test/support/vcr.rb:37:in `block in test'
rails test test/support/vcr.rb:36
E
Error:
ChatwootControllerTest#test_with_dynamic_botpress_bot_id:
Addressable::URI::InvalidURIError: Absolute URI missing hierarchical segment: 'http://:80'
    app/use_cases/chatwoot/send_to_botpress.rb:21:in `call!'
    app/use_cases/chatwoot/receive_event.rb:28:in `process_event'
    app/use_cases/chatwoot/receive_event.rb:7:in `call!'
    app/controllers/chatwoot_controller.rb:3:in `webhook'
    test/controllers/chatwoot_controller_test.rb:24:in `block in <class:ChatwootControllerTest>'
    test/support/vcr.rb:38:in `instance_eval'
    test/support/vcr.rb:38:in `block (2 levels) in test'
    test/support/vcr.rb:37:in `block in test'
rails test test/support/vcr.rb:36
E
Error:
DynamicBotIdTest#test_success:
Addressable::URI::InvalidURIError: Absolute URI missing hierarchical segment: 'http://:80'
    app/use_cases/chatwoot/send_to_botpress.rb:21:in `call!'
    app/use_cases/chatwoot/receive_event.rb:28:in `process_event'
    app/use_cases/chatwoot/receive_event.rb:7:in `call!'
    test/use_cases/chatwoot/receive_event/dynamic_bot_id_test.rb:14:in `block in <class:DynamicBotIdTest>'
    test/support/vcr.rb:38:in `instance_eval'
    test/support/vcr.rb:38:in `block (2 levels) in test'
    test/support/vcr.rb:37:in `block in test'
rails test test/support/vcr.rb:36
E
Error:
SendToChatwootTest#test_invalid_endpoint:
Addressable::URI::InvalidURIError: Absolute URI missing hierarchical segment: 'http://:80'
    app/use_cases/chatwoot/send_to_chatwoot_request.rb:14:in `call!'
    app/use_cases/chatwoot/send_to_chatwoot.rb:20:in `call!'
    test/use_cases/chatwoot/send_to_chatwoot_test.rb:34:in `block in <class:SendToChatwootTest>'
    test/support/vcr.rb:38:in `instance_eval'
    test/support/vcr.rb:38:in `block (2 levels) in test'
    test/support/vcr.rb:37:in `block in test'
rails test test/support/vcr.rb:36
E
Error:
SendToChatwootTest#test_success:
Addressable::URI::InvalidURIError: Absolute URI missing hierarchical segment: 'http://:80'
    app/use_cases/chatwoot/send_to_chatwoot_request.rb:14:in `call!'
    app/use_cases/chatwoot/send_to_chatwoot.rb:20:in `call!'
    test/use_cases/chatwoot/send_to_chatwoot_test.rb:20:in `block in <class:SendToChatwootTest>'
    test/support/vcr.rb:38:in `instance_eval'
    test/support/vcr.rb:38:in `block (2 levels) in test'
    test/support/vcr.rb:37:in `block in test'
rails test test/support/vcr.rb:36
E
Error:
SendToChatwootTest#test_invalid_token:
Addressable::URI::InvalidURIError: Absolute URI missing hierarchical segment: 'http://:80'
    app/use_cases/chatwoot/send_to_chatwoot_request.rb:14:in `call!'
    app/use_cases/chatwoot/send_to_chatwoot.rb:20:in `call!'
    test/use_cases/chatwoot/send_to_chatwoot_test.rb:65:in `block in <class:SendToChatwootTest>'
    test/support/vcr.rb:38:in `instance_eval'
    test/support/vcr.rb:38:in `block (2 levels) in test'
    test/support/vcr.rb:37:in `block in test'
rails test test/support/vcr.rb:36
E
Error:
SendToChatwootTest#test_invalid_account_id:
Addressable::URI::InvalidURIError: Absolute URI missing hierarchical segment: 'http://:80'
    app/use_cases/chatwoot/send_to_chatwoot_request.rb:14:in `call!'
    app/use_cases/chatwoot/send_to_chatwoot.rb:20:in `call!'
    test/use_cases/chatwoot/send_to_chatwoot_test.rb:42:in `block in <class:SendToChatwootTest>'
    test/support/vcr.rb:38:in `instance_eval'
    test/support/vcr.rb:38:in `block (2 levels) in test'
    test/support/vcr.rb:37:in `block in test'
rails test test/support/vcr.rb:36
E
Error:
SendToChatwootTest#test_invalid_conversation_id:
Addressable::URI::InvalidURIError: Absolute URI missing hierarchical segment: 'http://:80'
    app/use_cases/chatwoot/send_to_chatwoot_request.rb:14:in `call!'
    app/use_cases/chatwoot/send_to_chatwoot.rb:20:in `call!'
    test/use_cases/chatwoot/send_to_chatwoot_test.rb:50:in `block in <class:SendToChatwootTest>'
    test/support/vcr.rb:38:in `instance_eval'
    test/support/vcr.rb:38:in `block (2 levels) in test'
    test/support/vcr.rb:37:in `block in test'
rails test test/support/vcr.rb:36
E
Error:
SendToChatwootTest#test_invalid_content:
Addressable::URI::InvalidURIError: Absolute URI missing hierarchical segment: 'http://:80'
    app/use_cases/chatwoot/send_to_chatwoot_request.rb:14:in `call!'
    app/use_cases/chatwoot/send_to_chatwoot.rb:20:in `call!'
    test/use_cases/chatwoot/send_to_chatwoot_test.rb:58:in `block in <class:SendToChatwootTest>'
    test/support/vcr.rb:38:in `instance_eval'
    test/support/vcr.rb:38:in `block (2 levels) in test'
    test/support/vcr.rb:37:in `block in test'
rails test test/support/vcr.rb:36
E
Error:
SendToChatwootTest#test_options_response:
Addressable::URI::InvalidURIError: Absolute URI missing hierarchical segment: 'http://:80'
    app/use_cases/chatwoot/send_to_chatwoot_request.rb:14:in `call!'
    app/use_cases/chatwoot/send_to_chatwoot.rb:14:in `call!'
    test/use_cases/chatwoot/send_to_chatwoot_test.rb:27:in `block in <class:SendToChatwootTest>'
    test/support/vcr.rb:38:in `instance_eval'
    test/support/vcr.rb:38:in `block (2 levels) in test'
    test/support/vcr.rb:37:in `block in test'
rails test test/support/vcr.rb:36
E
Error:
SendToBotpressTest#test_invalid_bot:
Addressable::URI::InvalidURIError: Absolute URI missing hierarchical segment: 'http://:80'
    app/use_cases/chatwoot/send_to_botpress.rb:21:in `call!'
    test/use_cases/chatwoot/send_to_botpress_test.rb:31:in `block in <class:SendToBotpressTest>'
    test/support/vcr.rb:38:in `instance_eval'
    test/support/vcr.rb:38:in `block (2 levels) in test'
    test/support/vcr.rb:37:in `block in test'
rails test test/support/vcr.rb:36
.E
Error:
SendToBotpressTest#test_invalid_endpoint:
Addressable::URI::InvalidURIError: Absolute URI missing hierarchical segment: 'http://:80'
    app/use_cases/chatwoot/send_to_botpress.rb:21:in `call!'
    test/use_cases/chatwoot/send_to_botpress_test.rb:23:in `block in <class:SendToBotpressTest>'
    test/support/vcr.rb:38:in `instance_eval'
    test/support/vcr.rb:38:in `block (2 levels) in test'
    test/support/vcr.rb:37:in `block in test'
rails test test/support/vcr.rb:36
E
Error:
SendToBotpressTest#test_valid_event:
Addressable::URI::InvalidURIError: Absolute URI missing hierarchical segment: 'http://:80'
    app/use_cases/chatwoot/send_to_botpress.rb:21:in `call!'
    test/use_cases/chatwoot/send_to_botpress_test.rb:13:in `block in <class:SendToBotpressTest>'
    test/support/vcr.rb:38:in `instance_eval'
    test/support/vcr.rb:38:in `block (2 levels) in test'
    test/support/vcr.rb:37:in `block in test'
rails test test/support/vcr.rb:36
Finished in 0.228282s, 87.6111 runs/s, 21.9028 assertions/s.
20 runs, 5 assertions, 0 failures, 15 errors, 0 skips

what can i do now ?

**Comment by Double-Click-ERP** [comment]
another test on another VM

- followed these steps
https://www.linkedin.com/pulse/subindo-um-ambiente-de-desenvolvimento-chatbot-poderoso-douglas-lara/

Outgoing url :
> http://127.0.0.1:3000/chatwoot/webhook?botpress_bot_id=chatwoot&chatwoot_bot_token=LUmg5o9Ko6JoRknkgyjjFBYX

bot doesn't reply

**Comment by Double-Click-ERP** [comment]
p.s :
> http://127.0.0.1:3000/chatwoot/webhook?botpress_bot_id=chatwoot&chatwoot_bot_token=LUmg5o9Ko6JoRknkgyjjFBYX

![2023-06-21_12h50_20](https://github.com/douglara/chatwoot-botpress-bridge/assets/121224467/5a3faf42-56f2-4cc1-bea1-8dc6259b486f)

**Comment by Double-Click-ERP** [comment]
Hello @douglara ,
Yes this test is with docker

here you are :

> CONTAINER ID   IMAGE                                 COMMAND                  CREATED        STATUS        PORTS                                       NAMES
656e9d01f3db   chatwoot/chatwoot:v2.13.1             "sh -c 'bundle exec …"   22 hours ago   Up 22 hours   3000/tcp                                    chatwoot-botpress-bridge_chatwoot-sidekiq_1
555368cf9144   chatwoot/chatwoot:v2.13.1             "sh -c 'bundle exec …"   22 hours ago   Up 22 hours   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp   chatwoot-botpress-bridge_chatwoot_1
b0fa43b5350d   postgres:14                           "docker-entrypoint.s…"   22 hours ago   Up 22 hours   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp   chatwoot-botpress-bridge_postgres_1
87f79ff776af   botpress/server:v12_30_7              "/bin/sh -c './duckl…"   22 hours ago   Up 22 hours   0.0.0.0:3001->3000/tcp, :::3001->3000/tcp   chatwoot-botpress-bridge_botpress_1
850ce65b1c26   redis:alpine                          "docker-entrypoint.s…"   22 hours ago   Up 22 hours   0.0.0.0:6379->6379/tcp, :::6379->6379/tcp   chatwoot-botpress-bridge_redis_1
db4b5d179057   douglara/chatwoot-botpress-bridge:1   "/bin/sh -c 'bundle …"   22 hours ago   Up 22 hours   0.0.0.0:3002->3000/tcp, :::3002->3000/tcp   chatwoot-botpress-bridge_bridge_1

[850ce65b1c26.txt](https://github.com/douglara/chatwoot-botpress-bridge/files/11829566/850ce65b1c26.txt)
[555368cf9144.txt](https://github.com/douglara/chatwoot-botpress-bridge/files/11829567/555368cf9144.txt)
[b0fa43b5350d.txt](https://github.com/douglara/chatwoot-botpress-bridge/files/11829569/b0fa43b5350d.txt)
[db4b5d179057.txt](https://github.com/douglara/chatwoot-botpress-bridge/files/11829570/db4b5d179057.txt)
[87f79ff776af.txt](https://github.com/douglara/chatwoot-botpress-bridge/files/11829563/87f79ff776af.txt)
[656e9d01f3db.txt](https://github.com/douglara/chatwoot-botpress-bridge/files/11829565/656e9d01f3db.txt)

**Comment by Double-Click-ERP** [comment]
@douglara ?

**Comment by Double-Click-ERP** [comment]
Hello friend ,
that was an old wrong url , the correct url is in line 3264

> E, [2023-06-21T09:22:20.243304 #1] ERROR -- : [ActiveJob] [AgentBots::WebhookJob] [7141b064-2728-4306-b3b5-ec3a923162b6] Exception: invalid webhook url http://127.0.0.1:3001/chatwoot/webhook?botpress_bot_id=chatwoot&chatwoot_bot_token=LUmg5o9Ko6JoRknkgyjjFBYX : Failed to open TCP connection to 127.0.0.1:3001 (Connection refused - connect(2) for "127.0.0.1" port 3001)

**Comment by Double-Click-ERP** [comment]
> > p.s :
> > > http://127.0.0.1:3000/chatwoot/webhook?botpress_bot_id=chatwoot&chatwoot_bot_token=LUmg5o9Ko6JoRknkgyjjFBYX
> > 
> > 
> > ![2023-06-21_12h50_20](https://user-images.githubusercontent.com/121224467/247508407-5a3faf42-56f2-4cc1-bea1-8dc6259b486f.png)
> 
> line 6267
> 
> > E, [2023-06-22T06:06:09.537012 #1] ERROR -- : [ActiveJob] [AgentBots::WebhookJob] [40000660-e335-4586-857c-5cd74854e092] Exception: invalid webhook url http://10.0.0.99:3000/chatwoot/webhook?botpress_bot_id=chatwoot&chatwoot_bot_token=LUmg5o9Ko6JoRknkgyjjFBYX : 404 Not Found

@mattcam , did you got error 404?

**Comment by mattcam** [comment]
@Double-Click-ERP the discussion on this issued helped me with identifying my issue. I am unsure if with incorrect URL the request returned a 404, although I suspect it did. For me making the change as discussed in #13 which is to change `/chatroot/webhook` to `/chatwoot/webhook` returned success.

**Comment by Double-Click-ERP** [comment]
@mattcam , it is the correct url , but i get 404
could you please test your url ?

**Comment by Double-Click-ERP** [comment]
are you using IP ?

**Comment by mattcam** [comment]
> @mattcam , it is the correct url , but i get 404
> could you please test your url ?

Unable to retest as this service and others were only created for evaluation and has since been destroyed.

**Comment by Double-Click-ERP** [comment]
> > @mattcam , it is the correct url , but i get 404
> > could you please test your url ?
> 
> Unable to retest as this service and others were only created for evaluation and has since been destroyed.

Ok , Thank you

**Comment by Double-Click-ERP** [comment]
Hello @douglara ,
any update ?

**Comment by Double-Click-ERP** [comment]
Hello @douglara ,
any update ?

**Comment by douglara** [comment]
@Double-Click-ERP It seems problem with your environment.
Are you able to use it locally?

**Comment by Double-Click-ERP** [comment]
@douglara 
no
